Fix: Aggregation functions worked wrong on partitioned data.
tonlabs/ton-q-server pull request #136
Opened 2020-09-16 07:05 UTC by melsomino

2020-09-16 10:30 UTC, AlexeyVavilin approved these changes

2020-09-17 12:29 UTC, g9d requested changes

2020-09-17 12:29 UTC, g9d commented on __tests__/init-tests.js
>  const localDefs = {
unused

2020-09-17 12:29 UTC, g9d commented on __tests__/init-tests.js
> +export function createLocalArangoTestData(logs: QLogs): QBlockchainData {
if test used `createLocalArangoTestData`, we can't run this test in CI

2020-09-17 13:28 UTC, g9d approved these changes

2020-09-17 17:45 UTC, merged