Introduce BlockchainQuery to schema
tonlabs/ton-q-server pull request #191
Opened 2021-08-11 11:34 UTC by alex-novikov-1990

2021-08-11 14:04 UTC, melsomino requested changes
see comments

2021-08-11 14:04 UTC, melsomino commented on src/server/graphql/blockchain/blockchain.ts
> +                if (result.length > limit) {
`>= limit`? Because limit is args.first + 1

2021-08-11 14:04 UTC, melsomino commented on src/server/graphql/blockchain/blockchain.ts
> +                let helperTransaction: BlockchainTransaction | null = null;
Suggest to use `const hasMore = result.length >= limit`

2021-08-11 14:04 UTC, melsomino commented on src/server/graphql/blockchain/blockchain.ts
> +                let helperTransaction: BlockchainTransaction | null = null;
Suggest to use `const hasMore = result.length >= limit`

2021-08-11 14:04 UTC, melsomino commented on src/server/graphql/blockchain/blockchain.ts
> +                        hasNextPage: !!helperTransaction,
It depends on direction

2021-08-15 19:12 UTC, elasticLove1 requested changes
We need to define new blockchain queries as experimental

2021-08-16 12:57 UTC, melsomino approved these changes

2021-08-16 12:58 UTC, melsomino approved these changes

2021-08-16 14:06 UTC, merged