0.43.0 rc
tonlabs/ton-q-server pull request #192
Opened 2021-08-12 16:04 UTC by melsomino

2021-08-13 22:07 UTC, awnion requested changes

2021-08-13 22:07 UTC, awnion commented on res/type-defs-generated.graphql
> +	The formula is total_fees = in_msg.value - balance_delta - Sum(out_msg.value[]) - Sum(out_msg.fwd_fee[])
different style of almost the same description

2021-08-13 22:07 UTC, awnion commented on res/type-defs-generated.graphql
> +	balance_delta = in_msg.value - total_fees - Sum(out_msg.value[]) - Sum(out_msg.fwd_fee[])
here it's 2 lines and colon, I'd prefer this one, rather than one line

2021-08-13 22:58 UTC, awnion approved these changes

2021-09-21 08:56 UTC, elasticLove1 approved these changes

2021-09-22 14:54 UTC, merged