NEW: `capabilities_flags` companion field to p8 config parameter `cap…
tonlabs/ton-q-server pull request #289
Opened 2022-09-15 08:14 UTC by melsomino

…abilities`

2022-09-19 19:59 UTC, alex-novikov-1990 approved these changes

2022-09-20 14:30 UTC, elasticLove1 requested changes

2022-09-20 14:30 UTC, elasticLove1 commented on CHANGELOG.md
> +- `capabilities_flags` companion field to p8 config parameter `capabilities`
need to rename to `capability_flags`

2022-09-20 15:43 UTC, elasticLove1 approved these changes

2022-09-20 15:53 UTC, merged